// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Web uses the same Firebase project — add web app in Firebase Console
      // and replace these values with your web config if needed.
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        return android; // Safe fallback
    }
  }

  // ── Android (primary — from google-services.json) ──────────────────────────
  /// Firebase project ID — used for regional Cloud Function URLs.
  static const String firebaseProjectId = 'manabrahminmatri-de0ad';

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo-5h4Fa4m9DLSmUnHTl7dwVtTG-6BE9s',
    appId: '1:1058308497678:android:53d585e910e85464fcf75f',
    messagingSenderId: '1058308497678',
    projectId: firebaseProjectId,
    storageBucket: 'manabrahminmatri-de0ad.firebasestorage.app',
    authDomain: 'manabrahminmatri-de0ad.firebaseapp.com',
    databaseURL: 'https://manabrahminmatri-de0ad-default-rtdb.firebaseio.com',
  );

  // ── Windows / macOS / Linux / Web / iOS ───────────────────────────────────
  // ⚠️ CRITICAL: Each platform needs its own registered app in Firebase Console.
  // Go to Project Settings → Add app → Register each platform separately.
  // Using Android appId on other platforms causes Auth/FCM to fail silently.
  //
  // For development: Non-Android platforms fallback to Android config.
  // For production: Replace appId with platform-specific values from Firebase Console.
  
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo-5h4Fa4m9DLSmUnHTl7dwVtTG-6BE9s',
    // TODO: Register Windows app in Firebase Console and replace with actual appId
    // Format: 1:1058308497678:windows:HASH
    appId: '1:1058308497678:android:53d585e910e85464fcf75f', // Fallback to Android
    messagingSenderId: '1058308497678',
    projectId: 'manabrahminmatri-de0ad',
    storageBucket: 'manabrahminmatri-de0ad.firebasestorage.app',
    authDomain: 'manabrahminmatri-de0ad.firebaseapp.com',
    databaseURL: 'https://manabrahminmatri-de0ad-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo-5h4Fa4m9DLSmUnHTl7dwVtTG-6BE9s',
    // TODO: Register Web app in Firebase Console and replace with actual appId
    // Format: 1:1058308497678:web:HASH
    appId: '1:1058308497678:android:53d585e910e85464fcf75f', // Fallback to Android
    messagingSenderId: '1058308497678',
    projectId: 'manabrahminmatri-de0ad',
    storageBucket: 'manabrahminmatri-de0ad.firebasestorage.app',
    authDomain: 'manabrahminmatri-de0ad.firebaseapp.com',
    databaseURL: 'https://manabrahminmatri-de0ad-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo-5h4Fa4m9DLSmUnHTl7dwVtTG-6BE9s',
    // TODO: Register iOS app in Firebase Console and replace with actual appId
    // Format: 1:1058308497678:ios:HASH
    appId: '1:1058308497678:android:53d585e910e85464fcf75f', // Fallback to Android
    messagingSenderId: '1058308497678',
    projectId: 'manabrahminmatri-de0ad',
    storageBucket: 'manabrahminmatri-de0ad.firebasestorage.app',
    authDomain: 'manabrahminmatri-de0ad.firebaseapp.com',
    databaseURL: 'https://manabrahminmatri-de0ad-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo-5h4Fa4m9DLSmUnHTl7dwVtTG-6BE9s',
    // TODO: Register macOS app in Firebase Console and replace with actual appId
    // Format: 1:1058308497678:ios:HASH (macOS uses iOS type)
    appId: '1:1058308497678:android:53d585e910e85464fcf75f', // Fallback to Android
    messagingSenderId: '1058308497678',
    projectId: 'manabrahminmatri-de0ad',
    storageBucket: 'manabrahminmatri-de0ad.firebasestorage.app',
    authDomain: 'manabrahminmatri-de0ad.firebaseapp.com',
    databaseURL: 'https://manabrahminmatri-de0ad-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAo-5h4Fa4m9DLSmUnHTl7dwVtTG-6BE9s',
    // TODO: Register Linux app in Firebase Console and replace with actual appId
    // Note: Linux may need to use Web config or Android config
    appId: '1:1058308497678:android:53d585e910e85464fcf75f', // Fallback to Android
    messagingSenderId: '1058308497678',
    projectId: 'manabrahminmatri-de0ad',
    storageBucket: 'manabrahminmatri-de0ad.firebasestorage.app',
    authDomain: 'manabrahminmatri-de0ad.firebaseapp.com',
    databaseURL: 'https://manabrahminmatri-de0ad-default-rtdb.firebaseio.com',
  );
}
